# Generated by Django 2.0 on 2024-03-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='averaageRating',
            field=models.FloatField(default=0),
        ),
    ]
